### ISSUE TITLE
ImportError inside Docker container

### ISSUE THREAD

**Issue by itrushkin** [fastestimator/fastestimator#1031]
## Requirements
1. Docker

## Steps to reproduce

1. Run Python docker image: 
  ```bash
  docker run -it python:3.8 /bin/bash
  ```
  Also can be reproduced inside `ubuntu:18.04` after 
```
apt-get install python3.8
apt-get install python-dev python-pip
```

2. Install FastEstimator: 
```bash
pip install fastestimator tensorflow==2.4.1
```

3. Run Python:
```bash
python
```

4. Import FastEstimator:
```python
>>> import fastestimator
2021-06-03 14:35:36.543734: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-06-03 14:35:36.543761: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/fastestimator/__init__.py", line 15, in <module>        
    from fastestimator import architecture, backend, dataset, layers, op, schedule, summary, trace, util, xai
  File "/usr/local/lib/python3.8/site-packages/fastestimator/op/__init__.py", line 15, in <module>     
    from fastestimator.op import numpyop, tensorop
  File "/usr/local/lib/python3.8/site-packages/fastestimator/op/numpyop/__init__.py", line 15, in <module>
    from fastestimator.op.numpyop import meta, multivariate, univariate
  File "/usr/local/lib/python3.8/site-packages/fastestimator/op/numpyop/multivariate/__init__.py", line 17, in <module>
    from fastestimator.op.numpyop.multivariate.center_crop import CenterCrop
  File "/usr/local/lib/python3.8/site-packages/fastestimator/op/numpyop/multivariate/center_crop.py", line 18, in <module>
    from albumentations.augmentations.transforms import CenterCrop as CenterCropAlb
ImportError: cannot import name 'CenterCrop' from 'albumentations.augmentations.transforms' (/usr/local/lib/python3.8/site-packages/albumentations/augmentations/transforms.py)
```

I suppose this error occurs due to the latest release of `albumentations` because pinning to `albumentations==0.5.2` fixes it.

**Comment by TortoiseHam** [comment]
@itrushkin, thanks for reporting this. It's interesting, because our 1.2 release and master branch both have albumentations==0.5.2 pinned already in setup.py. What did you change to 'pin' it on your side?

**Comment by itrushkin** [comment]
I'm really sorry, the actual run was on the `1.1.2` version. Closing the issue. Importing the latest version works fine. Thank you!

**Comment by TortoiseHam** [comment]
No worries, let us know if anything else comes up :)
