### ISSUE TITLE
An error extracting .zip data in UNet example under win10

### ISSUE THREAD

**Issue by Alexandre-Huazhang-Li** [fastestimator/fastestimator#696]
Hi!

I'm not exactly sure if I'm posting on the correct place, please let me know if it is appropriate or not; greatly appreciate it!

My system is win10, with python 3.7 virtual environment.

I'm a new user to FastEstimator; when I was trying to run UNet lung segmentation example notebook, I get a keyerror when extracting the data; I was wondering if you could take a look, thanks a lot!

batch_size = 4
epochs = 25
max_train_steps_per_epoch = None
max_eval_steps_per_epoch = None
save_dir = tempfile.mkdtemp()
data_dir = None

csv = montgomery.load_data(root_dir=data_dir)

Extracting file ...
Traceback (most recent call last):

  File "C:\anaconda_install\envs\fe_env\lib\sre_parse.py", line 1015, in parse_template
    this = chr(ESCAPES[this][1])

KeyError: '\\l'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-13-e362f91346be>", line 8, in <module>
    csv = montgomery.load_data(root_dir=data_dir)

  File "C:\anaconda_install\envs\fe_env\lib\site-packages\fastestimator\dataset\data\montgomery.py", line 75, in load_data
    df['mask_left'] = df['image'].str.replace('CXR_png', os.path.join('ManualMask', 'leftMask'))

  File "C:\anaconda_install\envs\fe_env\lib\site-packages\pandas\core\strings.py", line 1954, in wrapper
    return func(self, *args, **kwargs)

  File "C:\anaconda_install\envs\fe_env\lib\site-packages\pandas\core\strings.py", line 2777, in replace
    self._parent, pat, repl, n=n, case=case, flags=flags, regex=regex

  File "C:\anaconda_install\envs\fe_env\lib\site-packages\pandas\core\strings.py", line 726, in str_replace
    return _na_map(f, arr, dtype=str)

  File "C:\anaconda_install\envs\fe_env\lib\site-packages\pandas\core\strings.py", line 131, in _na_map
    return _map_object(f, arr, na_mask=True, na_value=na_result, dtype=dtype)

  File "C:\anaconda_install\envs\fe_env\lib\site-packages\pandas\core\strings.py", line 216, in _map_object
    result = lib.map_infer_mask(arr, f, mask.view(np.uint8), convert)

  File "pandas\_libs\lib.pyx", line 2287, in pandas._libs.lib.map_infer_mask

  File "C:\anaconda_install\envs\fe_env\lib\site-packages\pandas\core\strings.py", line 714, in <lambda>
    f = lambda x: compiled.sub(repl=repl, string=x, count=n)

  File "C:\anaconda_install\envs\fe_env\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)

  File "C:\anaconda_install\envs\fe_env\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)

  File "C:\anaconda_install\envs\fe_env\lib\sre_parse.py", line 1018, in parse_template
    raise s.error('bad escape %s' % this, len(this))

error: bad escape \l

**Comment by vbvg2008** [comment]
Is this issue resolved?  May I ask what version are you using?

**Comment by vbvg2008** [comment]
@Alexandre-Huazhang-Li  Thanks for filing the issue, this is indeed the correct place to file issue, it's a little quiet here because we just release our first official version :).   

Anyway, the issue should be resolved in my recent PR #697 ,  if you install the most recent codebase by following the guide in readme, it should work.

**Comment by vbvg2008** [comment]
closing this issue as it is already resolved

**Comment by Alexandre-Huazhang-Li** [comment]
> @Alexandre-Huazhang-Li  Thanks for filing the issue, this is indeed the correct place to file issue, it's a little quiet here because we just release our first official version :).
> Anyway, the issue should be resolved in my recent PR #697 ,  if you install the most recent codebase by following the guide in readme, it should work.

Thank you so much; FE is very awesome!!
